# Generated by Django 5.0.6 on 2024-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfield',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestfield',
            name='prompt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
